import type { Deck } from "./common.types"

export const decks: Deck[] = [
	{
		id: "foyy4obvlh",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "qlsbefzq4fs",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "y03kj0ia9ke",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "lsya5lu5qy",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "uzk4zjthihd",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "2lz4u1ag3h3",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "v0fgxj0dtce",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "ygaotmybs0i",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "r6smbbqmb2d",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "hc42jmvfgzq",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "0vaihjsic51",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "qwydwfi211e",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "yriu1qlkp1",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "2fxq7jeuker",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "lt8zipipw4q",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "5ksyno5xgjj",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "ykv1wp3wy2",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "5y5jffezaqq",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "wzkocp5dsx9",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "0694w52evs0a",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "s9eqej2bnnj",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "ynhpqsoszs",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "b2hukw0rnjb",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "gtexpph3us7",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "6immdq65fv8",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "luwslohx8er",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "dicih35r0q",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "forbidden_test_1",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "forbidden_test_2",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "forbidden_test_3",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
]

export const forbiddenDecks: Deck[] = [
	{
		id: "forbidden_test_1",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "forbidden_test_2",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
	{
		id: "forbidden_test_3",
		vdbURL: "TODO: actual ",
		name: "TODO: actual deck name",
		archetypes: [],
	},
]
